CREATE TABLE parties (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  uuid VARCHAR(40) NOT NULL,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data TIMESTAMP NOT NULL
);